{% set version = "1.2.1" %}

package:
  name: xsel
  version: {{ version }}

source:
  url: https://github.com/kfish/xsel/archive/{{ version }}.tar.gz
  sha256: 18487761f5ca626a036d65ef2db8ad9923bf61685e06e7533676c56d7d60eb14

build:
  number: 6
  skip: true  # [win]
  ignore_run_exports:
    - xorg-libxt

requirements:
  build:
    - make
    - pkg-config
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make
    - autoconf
    - automake
    - gettext
    - libtool
  host:
    - xorg-libxt
    - xorg-libx11

test:
  commands:
    - 'xsel --help 2>&1 | grep -q "Usage: xsel \[options\]"'

about:
  home: https://www.vergenet.net/~conrad/software/xsel/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A command-line program for getting and setting the contents of the X selection
  dev_url: https://github.com/kfish/xsel

extra:
  recipe-maintainers:
    - ehfd
